name: Exécution automatique de Pay

on:
  schedule:
    - cron: "0 18 * * 6"  # Tous les samedis à 20h UTC
  workflow_dispatch:       # Permet un lancement manuel

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Installer les dépendances
        run: |
          pip install --upgrade pip
          pip install selenium

      - name: Exécuter le script Pay
        run: |
          python Pay.py
         env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ZIPCODE: ${{ secrets.ZIPCODE }}
      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: debug-screenshot
          path: debug.png
