name: Exécution automatique de Pay
on:
  schedule:
    - cron: "0 18 * * 6"
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python Pay.py
